log file /tmp/frr.log debug

debug zebra events
debug zebra vxlan
debug bgp zebra
debug zebra events
debug zebra nht
debug zebra srv6
debug zebra kernel
debug zebra rib detailed
debug zebra nexthop
debug bgp neighbor-events
debug bgp updates
debug bgp keepalives
debug bgp nht
debug bgp zebra
debug bfd network
debug bfd peer
debug bfd zebra

router bgp 65012
 bgp router-id 10.0.0.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check

 neighbor PE peer-group
 neighbor PE remote-as 65001
 neighbor 192.168.11.2 peer-group PE
 !
 address-family ipv4
  neighbor PE activate
  redistribute connected
 exit-address-family
 !
exit
!
end

