log file /tmp/frr.log debug

debug zebra events
debug zebra vxlan
debug bgp zebra
debug zebra events
debug zebra nht
debug zebra srv6
debug zebra kernel
debug zebra rib detailed
debug zebra nexthop
debug bgp neighbor-events
debug bgp updates
debug bgp keepalives
debug bgp nht
debug bgp zebra
debug bfd network
debug bfd peer
debug bfd zebra

ipv6 prefix-list BL seq 5 permit any
!
route-map BL-IN permit 1
 match ipv6 address prefix-list BL
 set ipv6 next-hop peer-address
exit
!

interface eth2
 ip router isis PE-ISIS
 ipv6 router isis PE-ISIS
 isis network point-to-point
exit

interface lo
 ip router isis PE-ISIS
 ipv6 router isis PE-ISIS
exit

router bgp 65500
 bgp router-id 172.31.250.102
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check

 neighbor BL peer-group
 neighbor BL remote-as 65500
 neighbor BL update-source fc00:0:0:1::12
 neighbor fd00:30:13::1 peer-group BL
 !
 segment-routing srv6
  locator MAIN
 exit
 !
 address-family ipv6 vpn
  neighbor fd00:30:13::1 activate
  neighbor fd00:30:13::1 route-map BL-IN in
 exit-address-family
 !
exit

router bgp 65500 vrf red
 bgp router-id 172.31.250.102
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 sid vpn per-vrf export auto
 !
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 172.31.250.102:2
  rt vpn both 65004:2
  export vpn
  import vpn
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
  rd vpn export 172.31.250.102:2
  rt vpn both 65004:2
  export vpn
  import vpn
 exit-address-family
exit
!
router isis PE-ISIS
 is-type level-1
 net 49.0000.1000.f006.0012.00
 topology ipv6-unicast
 log-adjacency-changes
 log-pdu-drops
 segment-routing on
 segment-routing srv6
  locator MAIN
 exit
exit
!
segment-routing
 srv6
  encapsulation
   source-address fd00:30:12::1
  locators
   locator MAIN
    prefix fd00:30:12::/48 block-len 32 node-len 16
    behavior usid
   exit
   !
  exit
  !
 exit
 !
 traffic-eng
 exit
exit
!
!
end

