log file /tmp/frr.log debug
debug zebra events
debug zebra nht
debug zebra srv6
debug zebra kernel
debug zebra rib detailed
debug zebra nexthop
interface lo
 ip router isis CORE
 ipv6 router isis CORE
exit
interface eth1
 ip router isis CORE
 ipv6 router isis CORE
exit
interface eth2
 ip router isis CORE
 ipv6 router isis CORE
 isis network point-to-point
exit
router bgp 65500
 bgp router-id 10.0.0.10
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 neighbor CLIENTS peer-group
 neighbor CLIENTS remote-as 65500
 neighbor CLIENTS update-source fc00:0:10::1
 neighbor fc00:0:1::1 peer-group CLIENTS
 neighbor fc00:0:2::1 peer-group CLIENTS
 neighbor fc00:0:3::1 peer-group CLIENTS
 neighbor fc00:0:20::1 peer-group CLIENTS
 address-family ipv4 vpn
  neighbor CLIENTS activate
  neighbor CLIENTS route-reflector-client
 exit-address-family
 address-family ipv6 vpn
  neighbor CLIENTS activate
  neighbor CLIENTS route-reflector-client
 exit-address-family
exit
router isis CORE
 net 49.0001.0000.0000.0010.00
 is-type level-1
 topology ipv6-unicast
 segment-routing on
 log-adjacency-changes
 log-pdu-drops
exit
end
