log file /tmp/frr.log debug

debug zebra events
debug zebra vxlan
debug zebra events
debug zebra nht
debug zebra srv6
debug zebra kernel
debug zebra rib detailed
debug zebra nexthop
debug bfd network
debug bfd peer
debug bfd zebra

interface eth0
 ipv6 router isis CORE
 isis network point-to-point
exit
!
interface eth1
 ipv6 router isis CORE
 isis network point-to-point
exit
!
interface eth2
 ipv6 router isis CORE
 isis network point-to-point
exit
!
router isis CORE
 net 49.0000.0000.0000.0001.00
 is-type level-1
 topology ipv6-unicast
 segment-routing on
exit
!
end

