log file /tmp/frr.log debug

debug zebra events
debug zebra vxlan
debug bgp zebra
debug zebra events
debug zebra nht
debug zebra srv6
debug zebra kernel
debug zebra rib detailed
debug zebra nexthop
debug bgp neighbor-events
debug bgp updates
debug bgp keepalives
debug bgp nht
debug bgp zebra
debug bfd network
debug bfd peer
debug bfd zebra

interface eth1
 ip router isis BL-ISIS
 ipv6 router isis BL-ISIS
 isis network point-to-point
exit

interface lo
 ip router isis BL-ISIS
 ipv6 router isis BL-ISIS
exit

router bgp 65500
 bgp router-id 172.31.250.103
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check

 neighbor AL peer-group
 neighbor AL remote-as 65500
 neighbor AL update-source lo
 neighbor fd00:30:12::1 peer-group AL
 !
 segment-routing srv6
  locator MAIN
 exit
 !
 address-family ipv6 vpn
  neighbor fd00:30:12::1 activate
 exit-address-family
 !
 !
exit

router bgp 65500 vrf red
 bgp router-id 172.31.250.103
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 sid vpn per-vrf export auto
 !
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 172.31.250.103:2
  rt vpn both 65004:2
  export vpn
  import vpn
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
  rd vpn export 172.31.250.103:2
  rt vpn both 65004:2
  export vpn
  import vpn
 exit-address-family
exit
!
router isis BL-ISIS
 is-type level-1
 net 49.0000.0000.0000.0003.00
 topology ipv6-unicast
 log-adjacency-changes
 log-pdu-drops
 segment-routing on
 segment-routing srv6
  locator MAIN
 exit
exit
!
segment-routing
 srv6
  encapsulation
   source-address fd00:30:13::1
  locators
   locator MAIN
    prefix fd00:30:13::/48 block-len 32 node-len 16
    behavior usid
   exit
   !
  exit
  !
 exit
 !
exit
!
!
end

